<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyTl4dF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyTl4dF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyTl4dF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyTl4dF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyTl4dF\App_KernelDevDebugContainer([
    'container.build_hash' => 'XyTl4dF',
    'container.build_id' => '916f400c',
    'container.build_time' => 1647549061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyTl4dF');
